<?PHP
ECHO "<!doctype HTML><HTML LANG='EN'><HEAD><META CHARSET='utf-8'><META NAME='VIEWPORT' CONTENT='WIDTH=DEVICE-WIDTH, INITIAL-SCALE=1.0'><TITLE>mATTY'S cOOLNESS</TITLE></HEAD><BODY><H1>mATTY IS COOL</H1><FORM><P><INPUT TYPE='RADIO' ID='MATTYiScOOL' NAME='MATTYcOOLNESS' VALUE='MATTYiScCHECKED><LABEL FOR='MATTYiScOOL'>mATTY IS COOL</LABEL></P><P><INPUT TYPE='RADIO' ID='MATTYiScOOLER' NAME='MATTYcOOLNESS' VALUE='MATTYiScOOLER'><LABEL FOR='MATTYiScOOLER'>mATTY IS COOLER</LABEL></P></FORM></BODY></HTML>";
?>

